In [1]:
import torch

In [2]:
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [3]:
print(torch.add(a,b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [4]:
print(torch.sub(a,b))

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [5]:
print(torch.mm(a,b))

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [6]:
print(torch.div(a,b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [7]:
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [8]:
print(torch.t(a))

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


In [9]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

In [ ]:
print(torch.cat((a,b),1))

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
c = a.reshape(1,4)

In [ ]:
c

tensor([[1, 2, 3, 4]])

In [10]:
import numpy as np

a = np.random.randn(3,3)

In [11]:
b = torch.from_numpy(a)

In [12]:
import torch

In [13]:
a = torch.ones((2,2), requires_grad = True)

In [ ]:
b = a+10

In [ ]:
c = b.mean()

In [ ]:
c

tensor(11., grad_fn=<MeanBackward0>)

In [ ]:
c.backward()

In [ ]:
a.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [15]:
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = torch.Tensor([[1],[1],[0]])

In [16]:
print(X)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]])


In [17]:
print(y)

tensor([[1.],
        [1.],
        [0.]])


In [18]:
def sigmoid(x):
  return 1/(1+torch.exp(-x))

In [19]:
def derivatives_sigmoid(x):
  return sigmoid(x) * (1-sigmoid(x))

In [20]:
epoch=7000
lr = 0.1
inputSize = X.shape[1]
hiddenSize = 3
outputSize = 1

In [21]:
# randomly initialize weight and biases
wh = torch.randn(inputSize, hiddenSize).type(torch.FloatTensor)
bh = torch.randn(1, hiddenSize).type(torch.FloatTensor)
wout = torch.randn(hiddenSize,outputSize)
bout = torch.randn(1,outputSize)

In [24]:
for i in range(epoch):
  #forward
  hidden_layer_input1 = torch.mm(X, wh)
  hidden_layer_input = hidden_layer_input1 + bh
  hidden_layer_activations = sigmoid(hidden_layer_input)

  output_layer_input1 = torch.mm(hidden_layer_activations, wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input)

  # backprop
  E = y-output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = E * slope_output_layer
  Error_at_hidden_layer = torch.mm(d_output, wout.t())
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

  # update weight & biases
  wout += torch.mm(hidden_layer_activations.t(), d_output)*lr
  bout += d_output.sum() * lr
  wh += torch.mm(X.t(), d_hiddenlayer) * lr
  bh += d_output.sum() * lr

In [26]:
print('actual:', y)

actual: tensor([[1.],
        [1.],
        [0.]])


In [27]:
print('predicted:', output)

predicted: tensor([[0.9965],
        [0.9963],
        [0.0055]])


In [7]:
%pylab inline
import os 
import numpy as np
import pandas as pd
from scipy.misc import imread
from sklearn.metrics import accuracy_score

Populating the interactive namespace from numpy and matplotlib


ImportError: ignored

In [6]:
!pip install Pillow